name: Merge Diff
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  mergeDiff:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.merged }} == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get diff
        run: git diff HEAD~1 -- A.txt > diff
      - name: Print diff
        run: cat diff

